### ISSUE TITLE
Index Out Of Range when selecting WiFi Adapter

### ISSUE THREAD

**Issue by gazivodag** [hmz777/NetStalker#16]
**Describe the bug**
I have 4 interfaces: vEthernet (WSL), 2 VMWare adapters, and my WiFi adapter.
When I choose my WiFi adapter at the bottom of the list, I am introduced to an index out of range exception.

**To Reproduce**
1. Select Wi-Fi at the bottom of the shown Network Adapters

**Expected behavior**
Not having this index exception

**Screenshots**
https://i.gyazo.com/66d64bfb128f4cba8607cf8ea8ee563c.png
https://i.gyazo.com/8b3dbfd52d61f10fe856064d1f2fdd4b.png
https://i.gyazo.com/15372367d336bd7003d8dc2d358eaa8a.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Release 3.0.1
- Stacktrace: `************** Exception Text **************
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at NetStalker.NicSelection.OkButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Additional context**
I didn't even have a chance to try out the program

**Comment by hmz777** [comment]
Hmm.. I'm not able to reproduce this, but, I noticed that you don't have the latest Npcap driver installed.
Most likely, it's not recognizing your wifi adapter as a `libpcap` device because of your current driver.
Try installing the latest driver from the provided link in the app description and update this issue with your findings.
