### ISSUE TITLE
problems in win 7

### ISSUE THREAD

**Issue by badrelmers** [hmz777/NetStalker#19]
Hi,

**Describe the bug**
in Win 7 64 (with latest updates) after running NetStalker (version: 4.1.0.0) for a  few minutes  I get this  error every time:

![image](https://user-images.githubusercontent.com/40046489/147481647-8e65c87e-7183-4e53-ada6-07e6e59845ee.png)
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.TypeLoadException: Could not find Windows Runtime type 'Windows.Data.Xml.Dom.XmlDocument'. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastContentBuilder.Show(CustomizeToast customize)
   at NetStalker.ToastNotifications.ToastAPI.ShowPrompt(String Content, NotificationPurpose Purpose, String DeviceIP, String DeviceMAC)
   at NetStalker.Main.Main_Resize(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.Form.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///D:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
NetStalker
    Assembly Version: 4.1.0.0
    Win32 Version: 4.1.0.0
    CodeBase: file:///D:/Program%20Files%20(x86)/Hamzi%20Alsheikh/NetStalker/NetStalker.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.Toolkit.Uwp.Notifications
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.2.1
    CodeBase: file:///D:/Program%20Files%20(x86)/Hamzi%20Alsheikh/NetStalker/Microsoft.Toolkit.Uwp.Notifications.DLL
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
DynamicComActivator
    Assembly Version: 0.0.0.0
    Win32 Version: 7.0.2.1
    CodeBase: file:///D:/Program%20Files%20(x86)/Hamzi%20Alsheikh/NetStalker/Microsoft.Toolkit.Uwp.Notifications.dll
----------------------------------------
ObjectListView
    Assembly Version: 2.9.1.1072
    Win32 Version: 2.9.1.0
    CodeBase: file:///D:/Program%20Files%20(x86)/Hamzi%20Alsheikh/NetStalker/ObjectListView.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3928.0 built by: NET48REL1
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Text.Json
    Assembly Version: 5.0.0.2
    Win32 Version: 5.0.521.16609
    CodeBase: file:///D:/Program%20Files%20(x86)/Hamzi%20Alsheikh/NetStalker/System.Text.Json.DLL
----------------------------------------
SharpPcap
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.0.0
    CodeBase: file:///D:/Program%20Files%20(x86)/Hamzi%20Alsheikh/NetStalker/SharpPcap.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
PacketDotNet
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///D:/Program%20Files%20(x86)/Hamzi%20Alsheikh/NetStalker/PacketDotNet.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///D:/Program%20Files%20(x86)/Hamzi%20Alsheikh/NetStalker/System.Memory.DLL
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0
    CodeBase: file:///D:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.20.51904
    CodeBase: file:///D:/Program%20Files%20(x86)/Hamzi%20Alsheikh/NetStalker/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```
is win 7 supported? if not do you have any plan to support it? thank you brother.

**Comment by hmz777** [comment]
@badrelmers Hello, to be honest, it's been a while since I tested NetStalker on Windows 7 but it should work fine on 
Win 7 64bit SP1.
The error you're seeing is due to the use of Microsoft's Windows 10 Toast Notifications library which does not support Windows 7.
Try disabling the notifications from options (before doing a scan) so they don't get called and restart the app.

**Comment by badrelmers** [comment]
yes now it works fine it never crashed again
thank you very very much
